services:
  mongo-cars:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_cars_data:/data/db

  mysql-carhire:
    image: mysql:latest
    ports:
      - 3308:3306
    volumes:
      - mysql_carhire_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  mysql-customer:
    image: mysql:latest
    ports:
      - 3307:3306
    volumes:
      - mysql_customer_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  car-service:
    depends_on:
      - mongo-cars
    image: kenzos/car-service
    ports:
      - 8081:8081
    links:
      - mongo-cars
    environment:
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo-cars

  customer-service:
    depends_on:
      - mysql-customer
    image: kenzos/customer-service
    ports:
      - 8082:8082
    links:
      - mysql-customer
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-customer
      MYSQL_DB_PORT: 3306

  carhire-service:
    depends_on:
      - car-service
      - customer-service
    image: kenzos/carhire-service
    ports:
      - 8083:8083
    links:
      - car-service
      - customer-service
    environment:
      CAR_SERVICE_BASEURL: car-service:8080
      CUSTOMER_INFO_SERVICE_BASEURL: customer-service:8082
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-carhire
      MYSQL_DB_PORT: 3306

#  api-gateway:
#    depends_on:
#      - car-service
#      - carhire-service
#    image: kenzos/api-gateway
#    ports:
#      - 8084:8084
#    links:
#      - car-service
#      - carhire-service
#    environment:
#      CAR_SERVICE_BASEURL: car-service:8081
#      _SERVICE_BASEURL: carhire-service:8083

volumes:
  mongodb_cars_data:
  mysql_customer_data:
  mysql_carhire_data:
