version: "3.8"

services:
  mongo-cars:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_car_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  mysql-carhire:
    image: mysql:latest
    ports:
      - 3308:3306
    volumes:
      - mysql_carhire_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: carhire_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 5
      interval: 30s
      start_period: 60s
      timeout: 5s

  mysql-customer:
    image: mysql:latest
    ports:
      - 3307:3306
    volumes:
      - mysql_customer_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: customer_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 5
      interval: 30s
      start_period: 60s
      timeout: 5s

  car-service:
    depends_on:
      - mongo-cars
    image: KenzoS/car-service
    ports:
      - 8080:8080
    environment:
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo-cars
    networks:
      - app-network

  customer-service:
    depends_on:
      mysql-customer:
        condition: service_healthy
    image: KenzoS/customer-service
    ports:
      - 8082:8082
    environment:
      MYSQL_DB_USERNAME: user
      MYSQL_DB_PASSWORD: password
      MYSQL_DB_HOST: mysql-customer
      MYSQL_DB_PORT: 3307
    networks:
      - app-network

  carhire-service:
    depends_on:
      mysql-carhire:
        condition: service_healthy
      customer-service:
        condition: service_healthy
    image: KenzoS/carhire-service
    ports:
      - 8081:8081
    environment:
      MYSQL_DB_USERNAME: user
      MYSQL_DB_PASSWORD: password
      MYSQL_DB_HOST: mysql-carhire
      MYSQL_DB_PORT: 3306
      PRODUCT_SERVICE_BASEURL: car-service:8080
      INVENTORY_INFO_SERVICE_BASEURL: customer-service:8082
    networks:
      - app-network

volumes:
  mongodb_car_data:
  mysql_customer_data:
  mysql_carhire_data:

networks:
  app-network:
    driver: bridge
