services:
  mongo-cars:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_car_data:/data/db
    networks:
      - app-network

  mysql-carhire:
    image: mysql:latest
    ports:
      - 3308:3306
    volumes:
      - mysql_carhire_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    networks:
      - app-network

  mysql-customer:
    image: mysql:latest
    ports:
      - 3307:3306
    volumes:
      - mysql_customer_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    networks:
      - app-network

  car-service:
    depends_on:
      - mongo-cars
    image: KenzoS/car-service
    ports:
      - 8080:8080
    environment:
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo-cars
    networks:
      - app-network

  customer-service:
    depends_on:
      - mysql-customer
    image: KenzoS/customer-service
    ports:
      - 8082:8082
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-customer
      MYSQL_DB_PORT: 3307
    networks:
      - app-network

  carhire-service:
    depends_on:
      - mysql-carhire
      - customer-service
    image: KenzoS/carhire-service
    ports:
      - 8081:8081
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-carhire
      MYSQL_DB_PORT: 3306
      PRODUCT_SERVICE_BASEURL: car-service:8080
      INVENTORY_INFO_SERVICE_BASEURL: customer-service:8082
    networks:
      - app-network

volumes:
  mongodb_car_data:
  mysql_customer_data:
  mysql_carhire_data:

networks:
  app-network:
    driver: bridge
