version: '3.8'

services:
  # MongoDB container voor Car Service
  MongoCar:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_cars_data:/data/db
    environment:
      MONGODB_HOST: MongoCar
      MONGODB_PORT: 27017

  # MySQL container voor CarHire Service
  MysqlCarHire:
    image: mysql:8.0.39
    ports:
      - 3308:3306
    volumes:
      - mysql_carhire_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: carhiredb  # Nieuwe naam voor CarHire database

  # MySQL container voor Customer Service
  MysqlCustomer:
    image: mysql:8.0.39
    ports:
      - 3307:3306
    volumes:
      - mysql_customer_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: customerdb  # Nieuwe naam voor Customer database

  # Car Service afhankelijk van MongoDB
  car-service:
    depends_on:
      - MongoCar
    image: kenzos/car-service
    ports:
      - 8081:8081
    environment:
      MONGODB_HOST: MongoCar
      MONGODB_PORT: 27017
    command: ["java", "-jar", "app.jar"]

  # Customer Service afhankelijk van MySQL Customer
  customer-service:
    depends_on:
      - MysqlCustomer
    image: kenzos/customer-service
    ports:
      - 8082:8082
    environment:
      MYSQL_DB_HOST: MysqlCustomer  # Verbindt met de nieuwe MySQL containernaam
      MYSQL_DB_PORT: 3306
    command: ["java", "-jar", "app.jar"]

  # CarHire Service afhankelijk van Car Service en Customer Service
  carhire-service:
    depends_on:
      - car-service
      - customer-service
    image: kenzos/carhire-service
    ports:
      - 8083:8083
    environment:
      CAR_SERVICE_BASEURL: car-service:8081
      CUSTOMER_INFO_SERVICE_BASEURL: customer-service:8082
      MYSQL_DB_HOST: MysqlCarHire  # Verbindt met de nieuwe MySQL containernaam
      MYSQL_DB_PORT: 3306
    command: ["java", "-jar", "app.jar"]

  # API Gateway afhankelijk van Car Service en CarHire Service
  api-gateway:
    depends_on:
      - car-service
      - carhire-service
    image: kenzos/api-gateway
    ports:
      - 8084:8084
    environment:
      CAR_SERVICE_BASEURL: car-service:8081
      CARHIRE_SERVICE_BASEURL: carhire-service:8083

  # Keycloak voor authenticatie
  keycloak:
    image: kenzos/keycloak:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8085:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    restart: unless-stopped

# Volumes voor data persistentie
volumes:
  mongodb_cars_data:
  mysql_customer_data:
  mysql_carhire_data:
  keycloak_data:
