version: '3.8'

services:
  MongoCar:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_cars_data:/data/db

  MysqlCarHire:
    image: mysql:latest
    ports:
      - 3308:3306
    volumes:
      - mysql_carhire_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  MysqlCustomer:
    image: mysql:latest
    ports:
      - 3307:3306
    volumes:
      - mysql_customer_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  car-service:
    depends_on:
      - MongoCar
    image: kenzos/car-service
    ports:
      - 8081:8084
    environment:
      MONGODB_HOST: MongoCar
      MONGODB_PORT: 27017

  customer-service:
    depends_on:
      - MysqlCustomer
    image: kenzos/customer-service
    ports:
      - 8082:8084
    environment:
      MYSQL_DB_HOST: MysqlCustomer
      MYSQL_DB_PORT: 3306

  carhire-service:
    depends_on:
      - car-service
      - customer-service
    image: kenzos/carhire-service
    ports:
      - 8083:8084
    environment:
      CAR_SERVICE_BASEURL: car-service:8081
      CUSTOMER_INFO_SERVICE_BASEURL: customer-service:8082
      MYSQL_DBUSERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: MysqlCarHire
      MYSQL_DB_PORT: 3306

  api-gateway:
    depends_on:
      - car-service
      - carhire-service
    image: kenzos/api-gateway
    ports:
      - 8084:8084
    environment:
      - WAIT_HOSTS=MysqlCarHire:3306,MysqlCustomer:3306

  keycloak:
    image: kenzos/keycloak:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8085:8085"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json  # Volume mapping for realm-import
    restart: unless-stopped
    command: [ "kc.sh", "start", "--import-realm" ]  # Start Keycloak with realm import

volumes:
  mongodb_cars_data:
  mysql_customer_data:
  mysql_carhire_data:
  keycloak_data:
