server:
  port: 8084

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  application:
    name: CAR-GATEWAY

  cloud:
    gateway:
      routes:
        # Route for Cars service (public access for all cars)
        - id: car-service-all
          uri: http://project-advanced-car-service-1:8081  # Use the container name for the CarService
          predicates:
            - Path=/api/cars/all  # Only this path is open for everyone (no authentication)
          filters:
            - SetPath=/api/cars/all

        # Route for CarService (secured access for creating, deleting, and updating cars)
        - id: car-service
          uri: http://project-advanced-car-service-1:8081  # Use the container name for the CarService
          predicates:
            - Path=/api/cars/**  # All other routes under /api/cars need authentication

        # Route for Customer Service (secured)
        - id: customer-service
          uri: http://project-advanced-customer-service-1:8082  # Use the container name for the CustomerService
          predicates:
            - Path=/api/customers/**  # All routes under /api/customers need authentication

        # Route for Car Hire Service (secured)
        - id: car-hire-service
          uri: http://project-advanced-carhire-service-1:8083  # Use the container name for the CarHireService
          predicates:
            - Path=/api/carhires/**  # All routes under /api/carhires need authentication

        # Identity service for OAuth2 login and authentication (public)
        - id: identity-service
          uri: http://project-advanced-keycloak-1:8085  # Use the container name for the IdentityService
          predicates:
            - Path=/auth/**  # Authentication and authorization service
          filters:
            - SetPath=/auth

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://project-advanced-keycloak-1:8085/realms/car-rental  # Identity service URI using container name
