name: Build and push Docker images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      # Bouw de car-service image
      - name: Build car-service Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/car-service:latest ./car-service

      - name: Push car-service Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/car-service:latest

      # Bouw de customer-service image
      - name: Build customer-service Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/customer-service:latest ./customer-service

      - name: Push customer-service Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/customer-service:latest

      # Bouw de carhire-service image
      - name: Build carhire-service Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/carhire-service:latest ./carhire-service

      - name: Push carhire-service Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/carhire-service:latest

      # Bouw de api-gateway image
      - name: Build api-gateway Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/api-gateway:latest ./api-gateway

      - name: Push api-gateway Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/api-gateway:latest

      # Bouw de keycloak image
      - name: Build keycloak Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/keycloak:latest ./keycloak

      - name: Push keycloak Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/keycloak:latest
